name: padsou
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  fonts:
    - family: Integral
      fonts:
        - asset: lib/assets/fonts/OTF/IntegralCF-Regular.otf
        - asset: lib\assets\fonts\OTF\IntegralCF-Bold.otf
          weight: 700
        - asset: lib\assets\fonts\OTF\IntegralCF-BoldOblique.otf
          weight: 600
          style: italic
        - asset: lib\assets\fonts\OTF\IntegralCF-DemiBold.otf
          weight: 600
        - asset: lib\assets\fonts\OTF\IntegralCF-ExtraBold.otf
          weight: 800
        - asset: lib\assets\fonts\OTF\IntegralCF-Heavy.otf
          weight: 900
        - asset: lib\assets\fonts\OTF\IntegralCF-HeavyOblique.otf
          weight: 900
          style: italic
        - asset: lib\assets\fonts\OTF\IntegralCF-Medium.otf
          weight: 500
        - asset: lib\assets\fonts\OTF\IntegralCF-MediumOblique.otf
          weight: 500
          style: italic
        - asset: lib\assets\fonts\OTF\IntegralCF-RegularOblique.otf
          style: italic
    - family: IntegralCF
      fonts:
        - asset: lib/assets/fonts/integral/IntegralCF-Bold.otf
          weight: 700
        - asset: lib/assets/fonts/integral/IntegralCF-BoldOblique.otf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/integral/IntegralCF-DemiBold.otf
          weight: 600
        - asset: lib/assets/fonts/integral/IntegralCF-DemiBoldOblique.otf
          weight: 600
          style: italic
        - asset: lib/assets/fonts/integral/IntegralCF-ExtraBold.otf
          weight: 800
        - asset: lib/assets/fonts/integral/IntegralCF-ExtraBoldOblique.otf
          weight: 800
          style: italic
        - asset: lib/assets/fonts/integral/IntegralCF-Heavy.otf
          weight: 900
        - asset: lib/assets/fonts/integral/IntegralCF-HeavyOblique.otf
          weight: 900
          style: italic
        - asset: lib/assets/fonts/integral/IntegralCF-Medium.otf
          weight: 500
        - asset: lib/assets/fonts/integral/IntegralCF-MediumOblique.otf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/integral/IntegralCF-Regular.otf
          weight: 400
        - asset: lib/assets/fonts/integral/IntegralCF-RegularOblique.otf
          weight: 400
          style: italic
    - family : inter
      fonts:
        - asset: lib/assets/fonts/inter/Inter-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/inter/Inter-Thin.ttf
          weight: 100
  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
    


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
