name: padsou
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IntegralCF
      fonts:
        - asset: lib/assets/fonts/integral/IntegralCF-Bold.otf
          weight: 700
        - asset: lib/assets/fonts/integral/IntegralCF-BoldOblique.otf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/integral/IntegralCF-DemiBold.otf
          weight: 600
        - asset: lib/assets/fonts/integral/IntegralCF-DemiBoldOblique.otf
          weight: 600
          style: italic
        - asset: lib/assets/fonts/integral/IntegralCF-ExtraBold.otf
          weight: 800
        - asset: lib/assets/fonts/integral/IntegralCF-ExtraBoldOblique.otf
          weight: 800
          style: italic
        - asset: lib/assets/fonts/integral/IntegralCF-Heavy.otf
          weight: 900
        - asset: lib/assets/fonts/integral/IntegralCF-HeavyOblique.otf
          weight: 900
          style: italic
        - asset: lib/assets/fonts/integral/IntegralCF-Medium.otf
          weight: 500
        - asset: lib/assets/fonts/integral/IntegralCF-MediumOblique.otf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/integral/IntegralCF-Regular.otf
          weight: 400
        - asset: lib/assets/fonts/integral/IntegralCF-RegularOblique.otf
          weight: 400
          style: italic
    - family : inter
      fonts:
        - asset: lib/assets/fonts/inter/Inter-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/inter/Inter-Thin.ttf
          weight: 100


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
