name: padsou
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  fonts:
    - family: Integral
      fonts:
        - asset: lib/assets/fonts/OTF/IntegralCF-Regular.otf
        - asset: lib\assets\fonts\OTF\IntegralCF-Bold.otf
          weight: 700
        - asset: lib\assets\fonts\OTF\IntegralCF-BoldOblique.otf
          weight: 600
          style: italic
        - asset: lib\assets\fonts\OTF\IntegralCF-DemiBold.otf
          weight: 600
        - asset: lib\assets\fonts\OTF\IntegralCF-ExtraBold.otf
          weight: 800
        - asset: lib\assets\fonts\OTF\IntegralCF-Heavy.otf
          weight: 900
        - asset: lib\assets\fonts\OTF\IntegralCF-HeavyOblique.otf
          weight: 900
          style: italic
        - asset: lib\assets\fonts\OTF\IntegralCF-Medium.otf
          weight: 500
        - asset: lib\assets\fonts\OTF\IntegralCF-MediumOblique.otf
          weight: 500
          style: italic
        - asset: lib\assets\fonts\OTF\IntegralCF-RegularOblique.otf
          style: italic
  assets:
    - lib/assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700